spring:
  #Allow Spring to spot put/delete requests from the html forms
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    #Turn off the logo
    banner-mode: off
  #Set database connection properties
  datasource:
    url: jdbc:mysql://localhost:3306/company
    username: root
    password: Kenan@sql#16
  #Set gmail connection properties
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #Turn off hibernates automatic validation before the persistence
  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none

#Add actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Data used throughout the application
application:
  security:
    #Data needed for the JWT
    jwt:
      secret-key: XfHU8rFEfmFAs8gxZyAfm2ddKokNHaM7T4ND83HTF8W9HEF79SB1RS7CN0IS7cop0OD3SF83N6SAX50KR4
      expiration: 86400000 # a day (represented in milliseconds)
      #86400000